apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Production environment. Patches the shared base with prod-specific values.
namespace: cosmos-production

resources:
  - ../../base

# patches:
#   - path: replicas.yaml
